config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:passwords], controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :users, skip: [:passwords], controllers: {
    sessions:      'devise/sessions',
    registrations: 'devise/registrations'
  }
  get 'admins/user_index', to: 'admins#user_index'
  get 'admins/shop_index', to: 'admins#shop_index'
  get '/users', to: redirect("/")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tops#top'
  resources :users do
  	get 'favs', to: 'favorites#index'
  end
  resources :shops do
  	resource :favorites, only: [:create, :destroy]
  	resource :comments, only: [:create]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shop, counter_cache: :favorites_count
end

app/models/shop.rb
class Shop < ApplicationRecord
  attachment :shop_image

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites, source: :user

  validates :shop_name, presence: true, length: {maximum: 50}
  validates :prefecture, presence: true
  validates :address, presence: true, length: {maximum: 100}
  validates :shop_description, length: {maximum: 400}
  validates :category, presence: true

  def favorite?(shop, user)
    shop.favorites.find_by(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  attachment :user_image

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :shops, through: :favorites, source: :shop

  validates :name, presence: true, length: {in: 2..20}
  validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}, length: {maximum: 50}
  validates :nickname, presence: true, length: {in: 2..20}
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!
  def user_index
  	@users = User.page(params[:page]).per(20).order(created_at: :desc)
  end

  def shop_index
  	@shops = Shop.page(params[:page]).per(20).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    shop = Shop.find(params[:shop_id])
    comment = current_user.comments.new(comment_params)
    comment.shop_id = shop.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_to shop_path(shop)
    else
      flash[:danger] = "コメントに失敗しました"
      redirect_to shop_path(shop)
    end
  end

  private

  def comment_params
  	params.require(:comment).permit(:content, :shop_id, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :set_shop, except: :index
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
  	@favorite = Favorite.create(user_id: current_user.id, shop_id: params[:shop_id])
  	@favorites = Favorite.where(shop_id: params[:shop_id])
  	@shop.reload
  end

  def destroy
  	favorite = Favorite.find_by(user_id: current_user.id, shop_id: params[:shop_id])
  	favorite.destroy
  	@favorites = Favorite.where(shop_id: params[:shop_id])
  	@shop.reload
  end

  def index
    @user = current_user
  	@favorites = Favorite.where(user_id: @user.id).all
  end

  private

  def set_shop
  	@shop = Shop.find(params[:shop_id])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!,  only: [:create, :edit, :update]
  before_action :authenticate_admin!, only: [:destroy]

  def show
  	@shop = Shop.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(shop_id: params[:id]).page(params[:page]).per(10).order(created_at: 'desc')
  end

  def new
  	@shop = Shop.new
  end

  def create
  	@shop = Shop.new(shop_params)
  	if @shop.save
  		flash[:success] = "新規投稿が成功しました"
  		redirect_to shop_path(@shop.id)
  	else
      flash[:danger] = "入力内容の確認をお願いします"
  		render 'new'
  	end
  end

  def edit
  	@shop = Shop.find(params[:id])
  end

  def update
  	@shop = Shop.find(params[:id])
  	@shop.update(shop_params)
  	if @shop.save
  		flash[:success] = "編集しました"
  		redirect_to shop_path(@shop)
  	else
      flash[:danger] = "編集内容の確認をお願いします"
  		render 'edit'
  	end
  end

  def index
    if params[:category] && params[:prefecture]
      @shops = Shop.where(prefecture: (params[:prefecture])).where(category: (params[:category])).page(params[:page]).per(20)
    else
      @shops = Shop.where(prefecture: (params[:prefecture])).page(params[:page]).per(20)
    end
  end

  def destroy
    @shop =  Shop.find(params[:id])
    if @shop.destroy
      flash[:success] = "削除しました"
      redirect_to admins_shop_index_path
    else
      flash[:danger] = "削除失敗しました"
      redirect_to admins_shop_index_path
    end
  end

  private

  def shop_params
  	params.require(:shop).permit(:shop_name, :shop_description, :shop_image, :prefecture, :address, :shop_url, :category)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
	def top
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!,  only: [:edit, :update]
  before_action :authenticate_admin!, only: [:destroy]

  def show
    @user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		flash[:success] = "プロフィールを編集しました"
  		redirect_to user_path(@user)
  	else
      flash[:danger] = "入力内容の確認をお願いします。"
  		render 'edit'
  	end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = "削除しました"
      redirect_to admins_user_index_path
    else
      flash[:danger] = "削除失敗しました"
      redirect_to admins_user_index_path
    end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :phone_number, :nickname, :user_description, :user_image)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    require "uri"

    def text_url_to_link text

      URI.extract(text, ['http']).uniq.each do |url|
        sub_text = ""
        sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"

        text.gsub!(url, sub_text)
    end

    return text
end

    def fav_counter(favorites)
  	  favorites.count
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite_form.html.erb
<% if user_signed_in? %>
    <% if shop.favorite?(shop, current_user) %>
        <%= button_to shop_favorites_path(shop_id: shop), method: :delete, remote: true, class: "fas fa-star fav-input-clear yellow" do %>
          <%= shop.favorites_count %>
        <% end %>
    <% else %>
        <%= button_to shop_favorites_path(shop_id: shop), remote: true, class: "far fa-star fav-input-clear" do %>
          <%= shop.favorites_count %>
        <% end %>
    <% end %>
<% else %>
    <div class="fas fa-star yellow fav-input-clear">
    	<%= shop.favorites_count %>
    </div>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-btn-<%= @shop.id %>").html("<%= j(render partial: 'favorite_form', locals: { shop: @shop }) %>")

app/views/favorites/destroy.js.erb
$("#favorite-btn-<%= @shop.id %>").html("<%= j(render partial: 'favorite_form', locals: { shop: @shop }) %>")

app/views/favorites/index.html.erb
<div class="container-fluid main">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2 class="h2">お気に入り一覧</h2>
            <% @favorites.each do |favorite| %>
            <% shop = Shop.find(favorite.shop_id) %>
            <div class="flex-container box1">
            	<div class="">
            		<%= attachment_image_tag shop, :shop_image, :fill, 150, 150,  fallback: "no_image.png", size: "150x150" %>
            	</div>
            	<div class="user-box overflow">
            		<div class="clearfix">
            			<h2 class="float-left name"><%= link_to shop.shop_name, shop_path(shop) %></h2>
            		</div>
            		<p class="index-shop-address">所在地：<%= shop.prefecture %><%= shop.address %></p>
                    <h3 class="index-com">コメント(<%= shop.comments.count %>)</h3>
            	</div>
                <div class="flex-container mt-10">
                    <i class="fas fa-star fav-input-clear yellow"></i>
                    <h3><%= shop.favorites_count %></h3>
                </div>
            </div>
            <% end %>

        </div>
    </div>
</div>

app/views/shops/edit.html.erb
<div class="container-fluid main">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2 class="h2">お店情報編集</h2>
            <%= form_for(@shop) do |f| %>
            <%= render 'layouts/error_messages', model: @shop %>
            <div class="flex-container">
                <div class="block mt-10">
                    <%= f.attachment_field :shop_image %>
                </div>
                <div class="block">
                    <label>店名</label>
                    <%= f.text_field :shop_name, autofocus: true, class: "form" %>
                    <label>都道府県</label>
                    <%= f.select :prefecture, [["北海道", "北海道"], ["青森県", "青森県"], ["岩手県", "岩手県"], ["宮城県", "宮城県"], ["秋田県", "秋田県"], ["山形県", "山形県"], ["福島県", "福島県"], ["茨城県", "茨城県"], ["栃木県", "栃木県"], ["群馬県", "群馬県"], ["埼玉県", "埼玉県"], ["千葉県", "千葉県"], ["東京都", "東京都"], ["神奈川県", "神奈川県"], ["新潟県", "新潟県"], ["富山県", "富山県"], ["石川県", "石川県"], ["福井県", "福井県"], ["山梨県", "山梨県"], ["長野県", "長野県"], ["岐阜県", "岐阜県"], ["静岡県", "静岡県"], ["愛知県", "愛知県"], ["三重県", "三重県"], ["滋賀県", "滋賀県"], ["京都府", "京都府"], ["大阪府", "大阪府"], ["兵庫県", "兵庫県"], ["奈良県", "奈良県"], ["和歌山県", "和歌山県"], ["鳥取県", "鳥取県"], ["島根県", "島根県"], ["岡山県", "岡山県"], ["広島県", "広島県"], ["山口県", "山口県"], ["徳島県", "徳島県"], ["香川県", "香川県"], ["愛媛県", "愛媛県"], ["高知県", "高知県"], ["福岡県", "福岡県"], ["佐賀県", "佐賀県"], ["長崎県", "長崎県"], ["熊本県", "熊本県"], ["大分県", "大分県"], ["宮崎県", "宮崎県"], ["鹿児島県", "鹿児島県"], ["沖縄県", "沖縄県"]] %>
                    <label>都道府県以下の住所</label>
                    <%= f.text_field :address, class: "form" %>
                    <label>SNS・サイトURL</label>
                    <%= f.text_field :shop_url, class: "form form-url" %>
                    <label>お店紹介文</label>
                    <%= f.text_area :shop_description, :size => "60x6", class: "form-l" %>
                </div>
            </div>
            <%= f.submit "保存する", class: "button float-right" %>
            <% end %>
        </div>
    </div>
</div>

app/views/shops/index.html.erb
<div class="container-fluid main">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2 class="h2"><%= "#{params[:prefecture]}" %>のお店一覧(<%= @shops.total_count %>件)</h2>
            <p class="index-shop-address">
            <%= link_to 'カフェ・喫茶店', shops_path(category: 'カフェ・喫茶店', prefecture: "#{params[:prefecture]}" ) %>/
            <%= link_to '古民家系', shops_path(category: '古民家系', prefecture: "#{params[:prefecture]}" ) %>/
            <%= link_to '宿・旅館', shops_path(category: '宿・旅館', prefecture: "#{params[:prefecture]}" ) %>/
            <%= link_to 'その他', shops_path(category: 'その他', prefecture: "#{params[:prefecture]}" ) %></p>
            <% @shops.each do |shop| %>
              <div class="flex-container box1">
                <div class="">
                    <%= attachment_image_tag shop, :shop_image, :fill, 150, 150,  fallback: "no_image.png", size: "150x150" %>
                </div>
                <div class="user-box overflow">
                    <div class="clearfix">
                        <h2 class="float-left name"><%= link_to shop.shop_name, shop_path(shop) %></h2>
                    </div>
                    <p class="index-shop-address">カテゴリ：<%= shop.category %></p>
                    <p class="index-shop-address">所在地：<%= shop.prefecture %><%= shop.address %></p>
                    <h3 class="index-com">コメント(<%= shop.comments.count %>)</h3>
                </div>
                <div class="flex-container mt-10">
                    <% if user_signed_in? %>
                    <% if shop.favorite?(shop, current_user) %>
                    <i class="fas fa-star fav-input-clear yellow"></i>
                    <h3><%= shop.favorites_count %></h3>
                    <% else %>
                    <i class="far fa-star fav-input-clear yellow"></i>
                    <h3><%= shop.favorites_count %></h3>
                    <% end %>
                    <% else %>
                    <i class="far fa-star yellow fav-input-clear"></i>
                    <h3><%= shop.favorites_count %></h3>
                    <% end %>
                </div>
            </div>
            <% end %>
            <%= paginate @shops %>
        </div>
    </div>
</div>

app/views/shops/new.html.erb
<div class="container-fluid main">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2 class="h2">お店新規登録</h2>
            <%= form_for(@shop) do |f| %>
            <%= render 'layouts/error_messages', model: @shop %>
            <div class="flex-container">
                <div class="block">
                    <%= f.attachment_field :shop_image %>
                </div>
                <div class="block">
                    <label>店名</label>
                    <%= f.text_field :shop_name, autofocus: true, class: "form" %>
                    <label>カテゴリー</label>
                    <%= f.select :category, [["カフェ・喫茶店", "カフェ・喫茶店"], ["古民家系", "古民家系"], ["宿・旅館", "宿・旅館"], ["その他", "その他"]], :prompt => "選択してください" %>
                    <label>都道府県</label>
                    <%= f.select :prefecture, [["北海道", "北海道"], ["青森県", "青森県"], ["岩手県", "岩手県"], ["宮城県", "宮城県"], ["秋田県", "秋田県"], ["山形県", "山形県"], ["福島県", "福島県"], ["茨城県", "茨城県"], ["栃木県", "栃木県"], ["群馬県", "群馬県"], ["埼玉県", "埼玉県"], ["千葉県", "千葉県"], ["東京都", "東京都"], ["神奈川県", "神奈川県"], ["新潟県", "新潟県"], ["富山県", "富山県"], ["石川県", "石川県"], ["福井県", "福井県"], ["山梨県", "山梨県"], ["長野県", "長野県"], ["岐阜県", "岐阜県"], ["静岡県", "静岡県"], ["愛知県", "愛知県"], ["三重県", "三重県"], ["滋賀県", "滋賀県"], ["京都府", "京都府"], ["大阪府", "大阪府"], ["兵庫県", "兵庫県"], ["奈良県", "奈良県"], ["和歌山県", "和歌山県"], ["鳥取県", "鳥取県"], ["島根県", "島根県"], ["岡山県", "岡山県"], ["広島県", "広島県"], ["山口県", "山口県"], ["徳島県", "徳島県"], ["香川県", "香川県"], ["愛媛県", "愛媛県"], ["高知県", "高知県"], ["福岡県", "福岡県"], ["佐賀県", "佐賀県"], ["長崎県", "長崎県"], ["熊本県", "熊本県"], ["大分県", "大分県"], ["宮崎県", "宮崎県"], ["鹿児島県", "鹿児島県"], ["沖縄県", "沖縄県"]], :prompt => "選択してください" %>
                    <label>都道府県以下の住所</label>
                    <%= f.text_field :address, class: "form form-url" %>
                    <label>SNS・サイトURL</label>
                    <%= f.text_field :shop_url, class: "form form-url" %>
                    <label>お店紹介文</label>
                    <%= f.text_area :shop_description, :size => "60x6", class: "form-l" %>
                </div>
            </div>
            <%= f.submit "保存する", class: "button float-right" %>
            <% end %>
        </div>
    </div>
</div>

app/views/shops/show.html.erb
<div class="container-fluid main">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h2 class="h2">お店情報</h2>
      <div class="flex-container">
        <div class="mt-10">
          <%= attachment_image_tag @shop, :shop_image, :fill, 200, 200,  fallback: "no_image.png", size: "200x200" %>
        </div>
        <div class="user-box overflow">
          <div class="clearfix">
            <h2 class="float-left name"><%= @shop.shop_name %>
              <% if current_user or current_admin %>
                <%= link_to edit_shop_path(@shop) do %>
                <i class="fas fa-cog"></i>
                <% end %></h2>
              <% end %>
              <div id="favorite-btn-<%= @shop.id %>" class="float-right mt-10">
                <%= render partial: 'favorites/favorite_form', locals: { shop: @shop} %>
              </div>
          </div>
          <p>カテゴリ：<%= @shop.category %></p>
            <p>所在地：<%= @shop.prefecture %><%= @shop.address %></p>
            <p>URL：<%= text_url_to_link(h(@shop.shop_url)).html_safe %></p>
            <p class="description"><%= @shop.shop_description %></p>
          </div>
        </div>
        <div class="com-top-border"></div>
        <div class="center">
          <h3>コメント(<%= @shop.comments.count %>)</h3>
          <div class="scroll-box inline-block">
            <% @shop.comments.each do |comment| %>
            <% unless comment.id.nil? %>
            <p class="comment-seperator"></p>
            <div class="comment-box">
              <%= link_to user_path(comment.user.id) do %><%= attachment_image_tag comment.user, :user_image, :fill, 30, 30, fallback: "no_image.png", size: "30x30" %><%= comment.user.nickname %>
              <% end %>
              <p><%= comment.content %></p>
            </div>
            <% end %>
            <% end %>
            <%= paginate @comments %>
          </div>
          <% if user_signed_in? %>
          <%= form_for [@shop, @comment] do |f| %>
            <%= f.text_area :content, :size => "40x5", class: "form-l inline-block" %>
            <%= f.submit "コメント", class: "button" %>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tops/top.html.erb
<div class="main-visual">
</div>

app/views/users/edit.html.erb
<div class="container-fluid main">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2 class="h2">ユーザー情報編集</h2>
            <%= form_for(@user) do |f| %>
            <%= render 'layouts/error_messages', model: @user %>
            <div class="flex-container">
                <div class="block mt-10">
                    <%= attachment_image_tag @user, :user_image, :fill, 150, 150, fallback: "no_image.png", size: "150x150" %>
                    <%= f.attachment_field :user_image %>
                </div>
                <div class="block">
                    <label>氏名</label>
                    <%= f.text_field :name, autofocus: true, class: "form" %>
                    <label>表示名</label>
                    <%= f.text_field :nickname, class: "form" %>
                    <label>メールアドレス</label>
                    <%= f.email_field :email, class: "form" %>
                    <label>電話番号</label>
                    <%= f.text_field :phone_number, class: "form" %>
                    <label>自己紹介</label>
                    <%= f.text_area :user_description, :size => "60x6", class: "form-l" %>
                </div>
            </div>
            <%= f.submit "保存する", class: "button float-right" %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid main">
  <div class="row">
	  <div class="col-md-6 col-md-offset-3">
      <h2 class="h2">ユーザー情報</h2>
      <div class="flex-container">
        <div class="mt-10">
          <%= attachment_image_tag @user, :user_image, :fill, 150, 150, fallback: "no_image.png", size: "150x150" %>
        </div>
        <div class="user-box overflow">
          <div class="clearfix">
            <h2 class="float-left name"><%= @user.nickname %>
              <% if current_user or current_admin %>
                <%= link_to edit_user_path(@user) do %>
                <i class="fas fa-cog"></i>
              <% end %>
            <% end %></h2>
          </div>
          <p class="description"><%= @user.user_description %></p>
        </div>
      </div>
      <p class="index-shop-address">◯<%= link_to "お気に入り", user_favs_path(@user) %></p>
      <p class="index-shop-address">◯<%= link_to "退会", @user, method: :delete, data: { confirm: "退会しますか？" } %></p>

    </div>
	</div>
</div>