config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:passwords], controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :users, skip: [:passwords], controllers: {
    sessions:      'devise/sessions',
    registrations: 'devise/registrations'
  }
  get 'admins/user_index', to: 'admins#user_index'
  get 'admins/shop_index', to: 'admins#shop_index'
  get '/users', to: redirect("/")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tops#top'
  resources :users do
  	get 'favs', to: 'favorites#index'
  end
  resources :shops do
  	resource :favorites, only: [:create, :destroy]
  	resource :comments, only: [:create]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shop, counter_cache: :favorites_count
end

app/models/shop.rb
class Shop < ApplicationRecord
  attachment :shop_image

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites, source: :user

  validates :shop_name, presence: true, length: {maximum: 50}
  validates :prefecture, presence: true
  validates :address, presence: true, length: {maximum: 100}
  validates :shop_description, length: {maximum: 400}
  validates :category, presence: true

  def favorite?(shop, user)
    shop.favorites.find_by(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  attachment :user_image

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :shops, through: :favorites, source: :shop

  validates :name, presence: true, length: {in: 2..20}
  validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}, length: {maximum: 50}
  validates :nickname, presence: true, length: {in: 2..20}
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!
  def user_index
  	@users = User.page(params[:page]).per(20).order(created_at: :desc)
  end

  def shop_index
  	@shops = Shop.page(params[:page]).per(20).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    shop = Shop.find(params[:shop_id])
    comment = current_user.comments.new(comment_params)
    comment.shop_id = shop.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_to shop_path(shop)
    else
      flash[:danger] = "コメントに失敗しました"
      redirect_to shop_path(shop)
    end
  end

  private

  def comment_params
  	params.require(:comment).permit(:content, :shop_id, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :set_shop, except: :index
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
  	@favorite = Favorite.create(user_id: current_user.id, shop_id: params[:shop_id])
  	@favorites = Favorite.where(shop_id: params[:shop_id])
  	@shop.reload
  end

  def destroy
  	favorite = Favorite.find_by(user_id: current_user.id, shop_id: params[:shop_id])
  	favorite.destroy
  	@favorites = Favorite.where(shop_id: params[:shop_id])
  	@shop.reload
  end

  def index
    @user = current_user
  	@favorites = Favorite.where(user_id: @user.id).all
  end

  private

  def set_shop
  	@shop = Shop.find(params[:shop_id])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!,  only: [:create, :edit, :update]
  before_action :authenticate_admin!, only: [:destroy]

  def show
  	@shop = Shop.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(shop_id: params[:id]).page(params[:page]).per(10).order(created_at: 'desc')
  end

  def new
  	@shop = Shop.new
  end

  def create
  	@shop = Shop.new(shop_params)
  	if @shop.save
  		flash[:success] = "新規投稿が成功しました"
  		redirect_to shop_path(@shop.id)
  	else
      flash[:danger] = "入力内容の確認をお願いします"
  		render 'new'
  	end
  end

  def edit
  	@shop = Shop.find(params[:id])
  end

  def update
  	@shop = Shop.find(params[:id])
  	@shop.update(shop_params)
  	if @shop.save
  		flash[:success] = "編集しました"
  		redirect_to shop_path(@shop)
  	else
      flash[:danger] = "編集内容の確認をお願いします"
  		render 'edit'
  	end
  end

  def index
    if params[:category] && params[:prefecture]
      @shops = Shop.where(prefecture: (params[:prefecture])).where(category: (params[:category])).page(params[:page]).per(20)
    else
      @shops = Shop.where(prefecture: (params[:prefecture])).page(params[:page]).per(20)
    end
  end

  def destroy
    @shop =  Shop.find(params[:id])
    if @shop.destroy
      flash[:success] = "削除しました"
      redirect_to admins_shop_index_path
    else
      flash[:danger] = "削除失敗しました"
      redirect_to admins_shop_index_path
    end
  end

  private

  def shop_params
  	params.require(:shop).permit(:shop_name, :shop_description, :shop_image, :prefecture, :address, :shop_url, :category)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
	def top
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!,  only: [:edit, :update]
  before_action :authenticate_admin!, only: [:destroy]

  def show
    @user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		flash[:success] = "プロフィールを編集しました"
  		redirect_to user_path(@user)
  	else
      flash[:danger] = "入力内容の確認をお願いします。"
  		render 'edit'
  	end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = "削除しました"
      redirect_to admins_user_index_path
    else
      flash[:danger] = "削除失敗しました"
      redirect_to admins_user_index_path
    end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :phone_number, :nickname, :user_description, :user_image)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    require "uri"

    def text_url_to_link text

      URI.extract(text, ['http']).uniq.each do |url|
        sub_text = ""
        sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"

        text.gsub!(url, sub_text)
    end

    return text
end

    def fav_counter(favorites)
  	  favorites.count
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shop_index.html.erb
<div class="container-fluid main">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>ショップ一覧</h1>
            <table>
                <tr>
                    <th>ID</th>
                    <th>画像</th>
                    <th>店名</th>
                    <th>記事作成日</th>
                    <th>記事削除</th>
                </tr>
                <% @shops.each do |shop| %>
                <tr>
                    <td><%= shop.id %></td>
                    <td><%= attachment_image_tag shop, :shop_image, :fill, 80, 80, fallback: "no_image.png", size: "80x80" %></td>
                    <td><%= link_to shop.shop_name, shop_path(shop) %></td>
                    <td><%= shop.created_at.strftime("%Y-%m-%d %H:%M") %></td>
                    <td><%= link_to "削除", shop, method: :delete, data: { confirm: "削除しますか？" } %></td>
                </tr>
                <% end %>
            </table>
            <%= paginate @shops %>
        </div>
    </div>
</div>

app/views/admins/user_index.html.erb
<div class="container-fluid main">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>ユーザー一覧</h1>
            <table>
                <tr>
                    <th>ID</th>
                    <th>画像</th>
                    <th>氏名</th>
                    <th>アカウント作成日</th>
                    <th>アカウント削除</th>
                </tr>
                <% @users.each do |user| %>
                <tr>
                    <td><%= user.id %></td>
                    <td><%= attachment_image_tag user, :user_image, :fill, 80, 80, fallback: "no_image.png", size: "80x80" %></td>
                    <td><%= link_to user.name, user_path(user) %></td>
                    <td><%= user.created_at.strftime("%Y-%m-%d %H:%M") %></td>
                    <td><%= link_to "削除", user, method: :delete, data: { confirm: "削除しますか？" } %></td>
                </tr>
                <% end %>
            </table>
            <%= paginate @users %>
        </div>
    </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_content">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>© 2019 HatakeyamaAya</p>
</footer>

app/views/layouts/_header.html.erb
<header>
    <ul class="nav">
      <li><%= link_to "猫とひと息", '/' %></li>
      <li>
            <p class="nav-text">北海道・東北</p>
              <ul>
                  <li><%= link_to '北海道', shops_path(prefecture: '北海道') %></li>
                  <li><%= link_to '青森県', shops_path(prefecture: '青森県') %></li>
                  <li><%= link_to '岩手県', shops_path(prefecture: '岩手県') %></li>
                  <li><%= link_to '宮城県', shops_path(prefecture: '宮城県') %></li>
                  <li><%= link_to '秋田県', shops_path(prefecture: '秋田県') %></li>
                  <li><%= link_to '山形県', shops_path(prefecture: '山形県') %></li>
                  <li><%= link_to '福島県', shops_path(prefecture: '福島県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">関東</p>
              <ul>
                  <li><%= link_to '茨城県', shops_path(prefecture: '茨城県') %></li>
                  <li><%= link_to '栃木県', shops_path(prefecture: '栃木県') %></li>
                  <li><%= link_to '群馬県', shops_path(prefecture: '群馬県') %></li>
                  <li><%= link_to '埼玉県', shops_path(prefecture: '埼玉県') %></li>
                  <li><%= link_to '千葉県', shops_path(prefecture: '千葉県') %></li>
                  <li><%= link_to '東京都', shops_path(prefecture: '東京都') %></li>
                  <li><%= link_to '神奈川県', shops_path(prefecture: '神奈川県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">中部</p>
              <ul>
                  <li><%= link_to '新潟県', shops_path(prefecture: '新潟県') %></li>
                  <li><%= link_to '富山県', shops_path(prefecture: '富山県') %></li>
                  <li><%= link_to '石川県', shops_path(prefecture: '石川県') %></li>
                  <li><%= link_to '福井県', shops_path(prefecture: '福井県') %></li>
                  <li><%= link_to '山梨県', shops_path(prefecture: '山梨県') %></li>
                  <li><%= link_to '長野県', shops_path(prefecture: '長野県') %></li>
                  <li><%= link_to '岐阜県', shops_path(prefecture: '岐阜県') %></li>
                  <li><%= link_to '静岡県', shops_path(prefecture: '静岡県') %></li>
                  <li><%= link_to '愛知県', shops_path(prefecture: '岐阜県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">近畿</p>
              <ul>
                  <li><%= link_to '三重県', shops_path(prefecture: '三重県') %></li>
                  <li><%= link_to '滋賀県', shops_path(prefecture: '滋賀県') %></li>
                  <li><%= link_to '奈良県', shops_path(prefecture: '奈良県') %></li>
                  <li><%= link_to '和歌山県', shops_path(prefecture: '和歌山県') %></li>
                  <li><%= link_to '京都府', shops_path(prefecture: '京都府') %></li>
                  <li><%= link_to '大阪府', shops_path(prefecture: '大阪府') %></li>
                  <li><%= link_to '兵庫県', shops_path(prefecture: '兵庫県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">中国・四国</p>
              <ul>
                  <li><%= link_to '岡山県', shops_path(prefecture: '岡山県') %></li>
                  <li><%= link_to '広島県', shops_path(prefecture: '広島県') %></li>
                  <li><%= link_to '鳥取県', shops_path(prefecture: '鳥取県') %></li>
                  <li><%= link_to '島根県', shops_path(prefecture: '島根県') %></li>
                  <li><%= link_to '山口県', shops_path(prefecture: '山口県') %></li>
                  <li><%= link_to '香川県', shops_path(prefecture: '香川県') %></li>
                  <li><%= link_to '徳島県', shops_path(prefecture: '徳島県') %></li>
                  <li><%= link_to '愛媛県', shops_path(prefecture: '愛媛県') %></li>
                  <li><%= link_to '高知県', shops_path(prefecture: '高知県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">九州・沖縄</p>
              <ul>
                  <li><%= link_to '福岡県', shops_path(prefecture: '福岡県') %></li>
                  <li><%= link_to '佐賀県', shops_path(prefecture: '佐賀県') %></li>
                  <li><%= link_to '長崎県', shops_path(prefecture: '長崎県') %></li>
                  <li><%= link_to '大分県', shops_path(prefecture: '大分県') %></li>
                  <li><%= link_to '熊本県', shops_path(prefecture: '熊本県') %></li>
                  <li><%= link_to '宮崎県', shops_path(prefecture: '宮崎県') %></li>
                  <li><%= link_to '鹿児島県', shops_path(prefecture: '鹿児島県') %></li>
                  <li><%= link_to '沖縄県', shops_path(prefecture: '沖縄県') %></li>
              </ul>
        </li>
        <li><p class="nav-text">新規登録/ログイン</p>
          <ul>
            <li><%= link_to "新規登録", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
          </ul>
        </li>
    </ul>
</header>

<script type='text/javascript'>
$(function() {
var nav = $('.nav');
$('li', nav)
.mouseover(function(e) {
$('ul', this).stop().slideDown('fast');
})
.mouseout(function(e) {
$('ul', this).stop().slideUp('fast');
});
});
</script>

app/views/layouts/_header_admin.html.erb
<header>
    <ul class="nav">
      <li><%= link_to "猫とひと息", '/' %></li>
      <li>
            <p class="nav-text">北海道・東北</p>
              <ul>
                  <li><%= link_to '北海道', shops_path(prefecture: '北海道') %></li>
                  <li><%= link_to '青森県', shops_path(prefecture: '青森県') %></li>
                  <li><%= link_to '岩手県', shops_path(prefecture: '岩手県') %></li>
                  <li><%= link_to '宮城県', shops_path(prefecture: '宮城県') %></li>
                  <li><%= link_to '秋田県', shops_path(prefecture: '秋田県') %></li>
                  <li><%= link_to '山形県', shops_path(prefecture: '山形県') %></li>
                  <li><%= link_to '福島県', shops_path(prefecture: '福島県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">関東</p>
              <ul>
                  <li><%= link_to '茨城県', shops_path(prefecture: '茨城県') %></li>
                  <li><%= link_to '栃木県', shops_path(prefecture: '栃木県') %></li>
                  <li><%= link_to '群馬県', shops_path(prefecture: '群馬県') %></li>
                  <li><%= link_to '埼玉県', shops_path(prefecture: '埼玉県') %></li>
                  <li><%= link_to '千葉県', shops_path(prefecture: '千葉県') %></li>
                  <li><%= link_to '東京都', shops_path(prefecture: '東京都') %></li>
                  <li><%= link_to '神奈川県', shops_path(prefecture: '神奈川県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">中部</p>
              <ul>
                  <li><%= link_to '新潟県', shops_path(prefecture: '新潟県') %></li>
                  <li><%= link_to '富山県', shops_path(prefecture: '富山県') %></li>
                  <li><%= link_to '石川県', shops_path(prefecture: '石川県') %></li>
                  <li><%= link_to '福井県', shops_path(prefecture: '福井県') %></li>
                  <li><%= link_to '山梨県', shops_path(prefecture: '山梨県') %></li>
                  <li><%= link_to '長野県', shops_path(prefecture: '長野県') %></li>
                  <li><%= link_to '岐阜県', shops_path(prefecture: '岐阜県') %></li>
                  <li><%= link_to '静岡県', shops_path(prefecture: '静岡県') %></li>
                  <li><%= link_to '愛知県', shops_path(prefecture: '岐阜県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">近畿</p>
              <ul>
                  <li><%= link_to '三重県', shops_path(prefecture: '三重県') %></li>
                  <li><%= link_to '滋賀県', shops_path(prefecture: '滋賀県') %></li>
                  <li><%= link_to '奈良県', shops_path(prefecture: '奈良県') %></li>
                  <li><%= link_to '和歌山県', shops_path(prefecture: '和歌山県') %></li>
                  <li><%= link_to '京都府', shops_path(prefecture: '京都府') %></li>
                  <li><%= link_to '大阪府', shops_path(prefecture: '大阪府') %></li>
                  <li><%= link_to '兵庫県', shops_path(prefecture: '兵庫県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">中国・四国</p>
              <ul>
                  <li><%= link_to '岡山県', shops_path(prefecture: '岡山県') %></li>
                  <li><%= link_to '広島県', shops_path(prefecture: '広島県') %></li>
                  <li><%= link_to '鳥取県', shops_path(prefecture: '鳥取県') %></li>
                  <li><%= link_to '島根県', shops_path(prefecture: '島根県') %></li>
                  <li><%= link_to '山口県', shops_path(prefecture: '山口県') %></li>
                  <li><%= link_to '香川県', shops_path(prefecture: '香川県') %></li>
                  <li><%= link_to '徳島県', shops_path(prefecture: '徳島県') %></li>
                  <li><%= link_to '愛媛県', shops_path(prefecture: '愛媛県') %></li>
                  <li><%= link_to '高知県', shops_path(prefecture: '高知県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">九州・沖縄</p>
              <ul>
                  <li><%= link_to '福岡県', shops_path(prefecture: '福岡県') %></li>
                  <li><%= link_to '佐賀県', shops_path(prefecture: '佐賀県') %></li>
                  <li><%= link_to '長崎県', shops_path(prefecture: '長崎県') %></li>
                  <li><%= link_to '大分県', shops_path(prefecture: '大分県') %></li>
                  <li><%= link_to '熊本県', shops_path(prefecture: '熊本県') %></li>
                  <li><%= link_to '宮崎県', shops_path(prefecture: '宮崎県') %></li>
                  <li><%= link_to '鹿児島県', shops_path(prefecture: '鹿児島県') %></li>
                  <li><%= link_to '沖縄県', shops_path(prefecture: '沖縄県') %></li>
              </ul>
        </li>
        <li>
          <p class="nav-text">admin</p>
            <ul>
              <li><%= link_to "ユーザー一覧", admins_user_index_path %></li>
              <li><%= link_to "お店一覧", admins_shop_index_path %></li>
              <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
            </ul>
        </li>
    </ul>
</header>

<script type='text/javascript'>
$(function() {
var nav = $('.nav');
$('li', nav)
.mouseover(function(e) {
$('ul', this).stop().slideDown('fast');
})
.mouseout(function(e) {
$('ul', this).stop().slideUp('fast');
});
});
</script>

app/views/layouts/_header_user.html.erb
<header>
    <ul class="nav">
    	<li><%= link_to "猫とひと息", '/' %></li>
    	<li>
            <p class="nav-text">北海道・東北</p>
              <ul>
                  <li><%= link_to '北海道', shops_path(prefecture: '北海道') %></li>
                  <li><%= link_to '青森県', shops_path(prefecture: '青森県') %></li>
                  <li><%= link_to '岩手県', shops_path(prefecture: '岩手県') %></li>
                  <li><%= link_to '宮城県', shops_path(prefecture: '宮城県') %></li>
                  <li><%= link_to '秋田県', shops_path(prefecture: '秋田県') %></li>
                  <li><%= link_to '山形県', shops_path(prefecture: '山形県') %></li>
                  <li><%= link_to '福島県', shops_path(prefecture: '福島県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">関東</p>
              <ul>
                  <li><%= link_to '茨城県', shops_path(prefecture: '茨城県') %></li>
                  <li><%= link_to '栃木県', shops_path(prefecture: '栃木県') %></li>
                  <li><%= link_to '群馬県', shops_path(prefecture: '群馬県') %></li>
                  <li><%= link_to '埼玉県', shops_path(prefecture: '埼玉県') %></li>
                  <li><%= link_to '千葉県', shops_path(prefecture: '千葉県') %></li>
                  <li><%= link_to '東京都', shops_path(prefecture: '東京都') %></li>
                  <li><%= link_to '神奈川県', shops_path(prefecture: '神奈川県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">中部</p>
              <ul>
                  <li><%= link_to '新潟県', shops_path(prefecture: '新潟県') %></li>
                  <li><%= link_to '富山県', shops_path(prefecture: '富山県') %></li>
                  <li><%= link_to '石川県', shops_path(prefecture: '石川県') %></li>
                  <li><%= link_to '福井県', shops_path(prefecture: '福井県') %></li>
                  <li><%= link_to '山梨県', shops_path(prefecture: '山梨県') %></li>
                  <li><%= link_to '長野県', shops_path(prefecture: '長野県') %></li>
                  <li><%= link_to '岐阜県', shops_path(prefecture: '岐阜県') %></li>
                  <li><%= link_to '静岡県', shops_path(prefecture: '静岡県') %></li>
                  <li><%= link_to '愛知県', shops_path(prefecture: '岐阜県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">近畿</p>
              <ul>
                  <li><%= link_to '三重県', shops_path(prefecture: '三重県') %></li>
                  <li><%= link_to '滋賀県', shops_path(prefecture: '滋賀県') %></li>
                  <li><%= link_to '奈良県', shops_path(prefecture: '奈良県') %></li>
                  <li><%= link_to '和歌山県', shops_path(prefecture: '和歌山県') %></li>
                  <li><%= link_to '京都府', shops_path(prefecture: '京都府') %></li>
                  <li><%= link_to '大阪府', shops_path(prefecture: '大阪府') %></li>
                  <li><%= link_to '兵庫県', shops_path(prefecture: '兵庫県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">中国・四国</p>
              <ul>
                  <li><%= link_to '岡山県', shops_path(prefecture: '岡山県') %></li>
                  <li><%= link_to '広島県', shops_path(prefecture: '広島県') %></li>
                  <li><%= link_to '鳥取県', shops_path(prefecture: '鳥取県') %></li>
                  <li><%= link_to '島根県', shops_path(prefecture: '島根県') %></li>
                  <li><%= link_to '山口県', shops_path(prefecture: '山口県') %></li>
                  <li><%= link_to '香川県', shops_path(prefecture: '香川県') %></li>
                  <li><%= link_to '徳島県', shops_path(prefecture: '徳島県') %></li>
                  <li><%= link_to '愛媛県', shops_path(prefecture: '愛媛県') %></li>
                  <li><%= link_to '高知県', shops_path(prefecture: '高知県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text">九州・沖縄</p>
              <ul>
                  <li><%= link_to '福岡県', shops_path(prefecture: '福岡県') %></li>
                  <li><%= link_to '佐賀県', shops_path(prefecture: '佐賀県') %></li>
                  <li><%= link_to '長崎県', shops_path(prefecture: '長崎県') %></li>
                  <li><%= link_to '大分県', shops_path(prefecture: '大分県') %></li>
                  <li><%= link_to '熊本県', shops_path(prefecture: '熊本県') %></li>
                  <li><%= link_to '宮崎県', shops_path(prefecture: '宮崎県') %></li>
                  <li><%= link_to '鹿児島県', shops_path(prefecture: '鹿児島県') %></li>
                  <li><%= link_to '沖縄県', shops_path(prefecture: '沖縄県') %></li>
              </ul>
        </li>
        <li>
            <p class="nav-text"><%= current_user.nickname %></p>
            <ul>
            	<li><%= link_to "プロフィール", user_path(current_user.id) %></li>
              <li><%= link_to "お店投稿", new_shop_path %></li>
            	<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>
        </li>
    </ul>
</header>

<script type='text/javascript'>
$(function() {
var nav = $('.nav');
$('li', nav)
.mouseover(function(e) {
$('ul', this).stop().slideDown('fast');
})
.mouseout(function(e) {
$('ul', this).stop().slideUp('fast');
});
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>猫とひと息</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" src="stylesheets/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  </head>

  <body>
    <div id="wrapper">
    <% if user_signed_in? %>
      <%= render 'layouts/header_user' %>
    <% elsif admin_signed_in? %>
      <%= render 'layouts/header_admin' %>
    <% else %>
      <%= render 'layouts/header' %>
    <% end %>
    <%= yield %>
  </div>
    <%= render 'layouts/footer' %>
  </body>
</html>